// Code generated by mockery v2.43.0. DO NOT EDIT.

package mock

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// ILimiter is an autogenerated mock type for the ILimiter type
type ILimiter struct {
	mock.Mock
}

type ILimiter_Expecter struct {
	mock *mock.Mock
}

func (_m *ILimiter) EXPECT() *ILimiter_Expecter {
	return &ILimiter_Expecter{mock: &_m.Mock}
}

// Expire provides a mock function with given fields: key, expiration
func (_m *ILimiter) Expire(key string, expiration time.Duration) error {
	ret := _m.Called(key, expiration)

	if len(ret) == 0 {
		panic("no return value specified for Expire")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, time.Duration) error); ok {
		r0 = rf(key, expiration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ILimiter_Expire_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Expire'
type ILimiter_Expire_Call struct {
	*mock.Call
}

// Expire is a helper method to define mock.On call
//   - key string
//   - expiration time.Duration
func (_e *ILimiter_Expecter) Expire(key interface{}, expiration interface{}) *ILimiter_Expire_Call {
	return &ILimiter_Expire_Call{Call: _e.mock.On("Expire", key, expiration)}
}

func (_c *ILimiter_Expire_Call) Run(run func(key string, expiration time.Duration)) *ILimiter_Expire_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(time.Duration))
	})
	return _c
}

func (_c *ILimiter_Expire_Call) Return(_a0 error) *ILimiter_Expire_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ILimiter_Expire_Call) RunAndReturn(run func(string, time.Duration) error) *ILimiter_Expire_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: key
func (_m *ILimiter) Get(key string) (string, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ILimiter_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ILimiter_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *ILimiter_Expecter) Get(key interface{}) *ILimiter_Get_Call {
	return &ILimiter_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *ILimiter_Get_Call) Run(run func(key string)) *ILimiter_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ILimiter_Get_Call) Return(_a0 string, _a1 error) *ILimiter_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ILimiter_Get_Call) RunAndReturn(run func(string) (string, error)) *ILimiter_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Incr provides a mock function with given fields: key
func (_m *ILimiter) Incr(key string) error {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Incr")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ILimiter_Incr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Incr'
type ILimiter_Incr_Call struct {
	*mock.Call
}

// Incr is a helper method to define mock.On call
//   - key string
func (_e *ILimiter_Expecter) Incr(key interface{}) *ILimiter_Incr_Call {
	return &ILimiter_Incr_Call{Call: _e.mock.On("Incr", key)}
}

func (_c *ILimiter_Incr_Call) Run(run func(key string)) *ILimiter_Incr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ILimiter_Incr_Call) Return(_a0 error) *ILimiter_Incr_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ILimiter_Incr_Call) RunAndReturn(run func(string) error) *ILimiter_Incr_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: key, value, expiration
func (_m *ILimiter) Set(key string, value interface{}, expiration time.Duration) error {
	ret := _m.Called(key, value, expiration)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}, time.Duration) error); ok {
		r0 = rf(key, value, expiration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ILimiter_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type ILimiter_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key string
//   - value interface{}
//   - expiration time.Duration
func (_e *ILimiter_Expecter) Set(key interface{}, value interface{}, expiration interface{}) *ILimiter_Set_Call {
	return &ILimiter_Set_Call{Call: _e.mock.On("Set", key, value, expiration)}
}

func (_c *ILimiter_Set_Call) Run(run func(key string, value interface{}, expiration time.Duration)) *ILimiter_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(interface{}), args[2].(time.Duration))
	})
	return _c
}

func (_c *ILimiter_Set_Call) Return(_a0 error) *ILimiter_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ILimiter_Set_Call) RunAndReturn(run func(string, interface{}, time.Duration) error) *ILimiter_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewILimiter creates a new instance of ILimiter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewILimiter(t interface {
	mock.TestingT
	Cleanup(func())
}) *ILimiter {
	mock := &ILimiter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
